###服务启动端口号
server:
  port: 8300
###服务名称(服务注册到eureka名称)
spring:
  application:
    name: app-easipay-member
###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8100/eureka

####swagger相关配置
swagger:
  base-package: net.easipay.member.service
  title: SpringCloud2.x构建微服务电商项目-微信服务接口
  description:
  version: 1.1
  terms-of-service-url: www.easipay.net
  contact:
    name: xxx
    email: xxx@qq.com

